SET IDENTITY_INSERT Employees ON
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (1, 'Cate', 'Denzilow', '97 Sutherland Junction', 'Taiyangling', '975875869');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (2, 'Tate', 'Alster', '63227 Hudson Avenue', 'Dallas', '915249080');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (3, 'Hobie', 'Whellans', '46120 Morrow Court', 'Limbi', '836037955');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (4, 'Harriott', 'Whaplington', '15318 Mariners Cove Alley', 'Yanac', '914030487');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (5, 'Conn', 'Ketley', '37233 Almo Pass', 'Pagersari', '820139117');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (6, 'Willabella', 'Dewi', '5 Anniversary Crossing', 'Rzeszów', '941229031');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (7, 'Georgie', 'Figgures', '92639 High Crossing Street', 'Jingang', '920775758');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (8, 'Athena', 'Junifer', '73838 Rusk Circle', 'Princeville', '939342309');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (9, 'Veronica', 'Bulpitt', '684 Goodland Street', 'Embalse', '997074698');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (10, 'Giffer', 'Odcroft', '64 Division Hill', 'Silikatnyy', '593715272');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (11, 'Jefferson', 'Roo', '19975 Cody Hill', 'Modis', '760723707');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (12, 'Welsh', 'Meachen', '2 Superior Park', 'Huntington', '942941779');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (13, 'Dasi', 'Davern', '582 Hanson Road', 'Regimin', '503920492');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (14, 'Brose', 'Spellworth', '7335 Reindahl Parkway', 'Lyon', '749493868');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (15, 'Carny', 'Petric', '60 Kipling Trail', 'Tunjë', '825929426');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (16, 'Joshua', 'Ziemens', '865 Graceland Point', 'Mīāndoāb', '718781757');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (17, 'Marjorie', 'Ennals', '2 Shoshone Alley', 'Osa', '568948749');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (18, 'North', 'Batsford', '096 4th Center', 'Berezanka', '520733076');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (19, 'Michael', 'Soldan', '8068 Burning Wood Avenue', 'Fukuchiyama', '672261424');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (20, 'Mariya', 'Hulmes', '25180 Loeprich Park', 'Pomabamba', '748945158');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (21, 'Colby', 'Abbots', '50 Porter Parkway', 'Qilin', '805672309');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (22, 'Gordon', 'Cloughton', '40 Oxford Junction', 'Chunyang', '549060284');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (23, 'Rianon', 'Minico', '52 Annamark Drive', 'Huangcun', '838520887');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (24, 'Murdock', 'Westphal', '42 Golf Course Junction', 'Concordia', '953949264');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (25, 'Papageno', 'Challice', '659 Colorado Park', 'Dordrecht', '892282849');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (26, 'Erminie', 'Elvidge', '0596 Veith Street', 'Quezaltepeque', '881415135');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (27, 'Sibelle', 'Dorran', '2199 Pearson Plaza', 'Partizan', '527474849');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (28, 'Madeleine', 'Ribchester', '43866 Utah Terrace', 'Ervedosa do Douro', '913633247');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (29, 'Averill', 'Bainton', '7 Russell Point', 'Sergach', '940834893');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (30, 'Trixy', 'Kollaschek', '46 Almo Alley', 'Perrelos', '926235305');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (31, 'Cortie', 'Gidley', '7 Doe Crossing Pass', 'Xinbao', '962735290');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (32, 'Bevin', 'Pressland', '643 Holmberg Center', 'Dengfeng', '881160651');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (33, 'Lucille', 'Kumaar', '465 Corben Alley', 'Qiganjidie', '775112497');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (34, 'Paulette', 'Ramsbottom', '023 Dryden Lane', 'Mercedes', '950166154');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (35, 'Rosy', 'Woolatt', '792 Summerview Court', 'Coronda', '574433665');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (36, 'Rockie', 'Kleisel', '71436 Paget Terrace', 'Slobodka', '917947786');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (37, 'Annamaria', 'Jowling', '188 Kenwood Trail', 'Pecna', '826862316');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (38, 'Isahella', 'Sears', '23 Lawn Crossing', 'El Paso', '852799470');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (39, 'Sascha', 'Standrin', '53697 Grim Street', 'Buliran', '812950089');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (40, 'Angel', 'Jenman', '74 Milwaukee Place', 'Chengzihe', '922711745');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (41, 'Jarrod', 'Resun', '2 Talmadge Road', 'El Tejocote', '934910176');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (42, 'Meagan', 'Le Maitre', '892 Jackson Center', 'Krasnogvardeyets', '924334323');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (43, 'Clair', 'Zanazzi', '4710 Brentwood Avenue', 'Malitbog', '623305626');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (44, 'Marnia', 'Mettetal', '1906 Iowa Junction', 'Wārāh', '664314801');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (45, 'Finlay', 'Vitall', '1 Sullivan Plaza', 'Lípa', '951553158');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (46, 'Clementia', 'Grgic', '6 Moulton Plaza', 'Rrasa e Sipërme', '891691525');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (47, 'Garv', 'Peplow', '3761 Havey Junction', 'Federal', '971657493');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (48, 'Gennifer', 'Breen', '459 Leroy Road', 'Iganga', '943710886');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (49, 'Freda', 'Lambrook', '0080 Michigan Place', 'Pavlivka', '718245715');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (50, 'Car', 'Rowan', '39 Lakewood Avenue', 'Oslo', '831819118');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (51, 'Artus', 'Carne', '517 Walton Alley', 'Janja', '876566164');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (52, 'Sherrie', 'Dargan', '658 Longview Trail', 'Saint-Quentin-en-Yvelines', '904747328');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (53, 'Xaviera', 'Spridgeon', '9645 Jenifer Avenue', 'Kondinskoye', '953416533');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (54, 'Allyce', 'Courcey', '44 Mallory Drive', 'Gorang', '843586111');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (55, 'Janella', 'Benoi', '3051 Pankratz Place', 'Železná Ruda', '585330578');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (56, 'Maridel', 'Twomey', '18 Hanover Junction', 'Puračić', '877291709');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (57, 'Ichabod', 'Boler', '25648 Daystar Pass', 'Noyemberyan', '737515024');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (58, 'Madlen', 'Sinnocke', '35 Twin Pines Drive', 'Guofu', '764670331');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (59, 'Earlie', 'Allard', '798 Pennsylvania Junction', 'Boshan', '994219505');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (60, 'Nathalia', 'Sherred', '1133 Kingsford Way', 'Qingsong', '999703148');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (61, 'Edik', 'Rijkeseis', '63767 Surrey Lane', 'Kiambu', '876299843');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (62, 'Guillemette', 'Legister', '36 Tennessee Junction', 'Obsza', '783386592');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (63, 'Emmye', 'Olifaunt', '94655 Manufacturers Park', 'Vũng Tàu', '912249850');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (64, 'Carree', 'Rootham', '960 Sommers Street', 'Piekoszów', '630832193');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (65, 'Weider', 'Hall-Gough', '5 Banding Alley', 'Guanajuato', '819132987');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (66, 'Darbee', 'Held', '218 Springs Way', 'Neftçala', '803762384');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (67, 'Dominick', 'Orrill', '3 Armistice Circle', 'Baume-les-Dames', '941315126');
insert into Employees (EmployeeID, FirstName, LastName, Address, City, Phone) values (68, 'Dorene', 'Armand', '6830 Sullivan Plaza', 'Mlandizi', '862928148');
SET IDENTITY_INSERT Employees OFF