insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (1, 'Keebler, Padberg and Zemlak', '1994285678', '5580 Norway Maple Pass', 'Tanzania', 'Kyaka', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (2, 'Treutel, Halvorson and Berge', '5791447449', '3 Hoepker Place', 'Poland', 'Dziewin', '32-708');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (3, 'Steuber Group', '8408650732', '8 Northridge Street', 'China', 'Yangchao', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (4, 'Stoltenberg LLC', '1141053410', '0957 Autumn Leaf Park', 'Philippines', 'Basiao', '5806');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (5, 'Wintheiser Group', '8453952683', '158 Shelley Pass', 'Philippines', 'Pagsabangan', '3318');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (6, 'Welch LLC', '4275884228', '976 La Follette Park', 'Madagascar', 'Fianarantsoa', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (7, 'Terry, Pacocha and Mueller', '4901377156', '4617 Park Meadow Terrace', 'China', 'Yangxu', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (8, 'Ritchie-Rice', '6065610733', '358 Sachs Drive', 'China', 'Gunziying', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (9, 'Stamm-Hickle', '8051689296', '2 Quincy Center', 'Armenia', 'Getahovit', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (10, 'Stiedemann, Bradtke and Effertz', '1165885889', '4453 Village Green Hill', 'Poland', 'Krzynowłoga Mała', '06-316');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (11, 'Nikolaus, Beer and O''Connell', '4477442652', '978 7th Alley', 'China', 'Anwen', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (12, 'Okuneva Group', '5733295665', '443 Cordelia Street', 'Thailand', 'Nong Chik', '94170');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (13, 'King, Pollich and Howe', '5224813172', '695 Lillian Alley', 'Bangladesh', 'Khulna', '9242');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (14, 'Doyle-Turcotte', '8545841346', '4 Almo Center', 'Sweden', 'Bromma', '168 58');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (15, 'Wolf LLC', '7753620406', '43099 Holy Cross Court', 'Dominican Republic', 'Cotuí', '10210');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (16, 'McCullough-Bogisich', '8285835187', '578 Orin Circle', 'Ukraine', 'Krasnosilka', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (17, 'Collins and Sons', '7117540204', '63 Debs Alley', 'Indonesia', 'Leran Kulon', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (18, 'Wisozk and Sons', '7836737187', '5635 Fieldstone Place', 'Philippines', 'Bacag', '8603');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (19, 'Bosco, Borer and Zieme', '5469369011', '6774 Carpenter Junction', 'Thailand', 'Tha Bo', '43110');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (20, 'Barton LLC', '5358790393', '0 Ramsey Circle', 'Brazil', 'Pelotas', '96000-000');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (21, 'Cummerata, Wisozk and Heathcote', '1069250091', '05 Morning Parkway', 'Portugal', 'Boleiros', '2495-313');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (22, 'Hickle-Batz', '7489749859', '46441 Monument Point', 'Indonesia', 'Sabang', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (23, 'Oberbrunner, Miller and Wisoky', '8001503150', '95 Spohn Place', 'Costa Rica', 'Esquipulas', '20706');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (24, 'Shields Inc', '6896082290', '9 Oriole Terrace', 'Venezuela', 'Ciudad Guayana', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (25, 'Metz-Cummings', '8592176025', '9 Waxwing Junction', 'China', 'Jiamaogong', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (26, 'Ward Group', '5303152466', '9088 Mcguire Place', 'Pakistan', 'Lakki Marwat', '28420');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (27, 'Mitchell, Schimmel and Schaden', '5023896487', '6183 Park Meadow Park', 'Tajikistan', 'Vakhsh', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (28, 'Rohan LLC', '1611036737', '2 Di Loreto Place', 'Colombia', 'La Victoria', '155007');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (29, 'Douglas, Murphy and Green', '5891002383', '001 Jenifer Point', 'Russia', 'Knyaginino', '606340');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (30, 'Boyle-Leannon', '6201356202', '667 Anzinger Trail', 'Comoros', 'Mirontsi', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (31, 'Schuppe, Jacobs and Beatty', '6989327109', '809 Helena Lane', 'China', 'Guanyinsi', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (32, 'Morissette-Pouros', '4284356903', '54181 Hollow Ridge Trail', 'Uzbekistan', 'Quva', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (33, 'Bode, Hickle and Torphy', '7899740035', '09877 Myrtle Center', 'Philippines', 'Looc', '5507');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (34, 'Upton-Senger', '2664731862', '13216 Bowman Circle', 'Honduras', 'Gracias', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (35, 'Bergnaum, Graham and Hagenes', '6463828722', '8 Mallory Road', 'Canada', 'La Sarre', 'J9Z');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (36, 'McGlynn-Williamson', '1169884513', '0 Prairieview Crossing', 'Philippines', 'Talalora', '6719');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (37, 'Johns and Sons', '4514323956', '807 Banding Junction', 'Philippines', 'Talisay', '4602');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (38, 'Adams, Stoltenberg and Walsh', '9754724997', '1707 Starling Point', 'China', 'Litan', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (39, 'Bergnaum-Schmitt', '7267897729', '97 Hooker Park', 'Indonesia', 'Sendang', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (40, 'Oberbrunner Inc', '6289448656', '4503 Washington Avenue', 'Madagascar', 'Ambarakaraka', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (41, 'Marvin, Hilll and Pfeffer', '3825307252', '0129 Toban Terrace', 'Peru', 'Cajacay', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (42, 'Cronin-Bernhard', '3886344919', '87292 Debra Avenue', 'China', 'Hongzhou', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (43, 'Koss, Bode and Cormier', '1261606580', '5 Loomis Way', 'Indonesia', 'Modis', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (44, 'Murray and Sons', '6025395664', '6361 Novick Junction', 'Greece', 'Néa Filadélfeia', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (45, 'Mann-Ryan', '2004321524', '22446 Colorado Hill', 'Ukraine', 'Kozelets’', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (46, 'Feil-Ullrich', '3232916890', '618 Dorton Way', 'United States', 'Long Beach', '90805');
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (47, 'Lind Inc', '9238861863', '02 Huxley Drive', 'Peru', 'Otuzco', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (48, 'Cronin LLC', '9191079715', '076 Stoughton Hill', 'China', 'Pinglumiao', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (49, 'Abernathy-Botsford', '3811493692', '1 Lukken Plaza', 'Israel', 'Yehud', null);
insert into Organizers (OrganizerID, CompanyName, Phone, Addres, Country, City, PostalCode) values (50, 'Von and Sons', '8709115528', '62 Oak Valley Alley', 'Russia', 'Starobelokurikha', '659633');
