EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 1
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 1
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 1
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 1
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 2
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 2
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 2
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 3
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 3
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 3
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 4
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 4
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 4
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 5
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 5
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 5
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 6
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 6
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 6
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 7
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 7
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 7
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 8
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 8
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 8
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 8
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 9
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 9
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 9
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 9
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 10
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 10
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 10
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 11
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 11
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 11
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 11
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 12
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 12
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 12
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 13
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 13
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 13
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 13
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 14
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 14
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 14
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 14
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 15
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 15
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 15
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 15
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 16
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 16
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 16
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 16
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 17
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 17
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 17
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 17
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 18
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 18
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 18
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 19
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 19
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 19
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 20
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 20
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 20
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 20
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 21
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 21
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 21
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 22
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 22
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 22
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 23
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 23
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 23
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 24
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 24
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 24
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 24
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 25
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 25
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 25
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 25
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 26
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 26
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 26
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 27
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 27
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 27
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 27
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 28
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 28
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 28
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 29
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 29
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 29
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 30
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 30
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 30
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 31
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 31
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 31
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 31
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 32
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 32
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 32
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 33
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 33
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 33
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 33
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 34
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 34
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 34
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 35
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 35
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 35
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 36
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 36
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 36
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 37
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 37
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 37
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 38
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 38
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 38
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 38
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 39
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 39
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 39
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 40
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 40
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 40
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 41
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 41
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 41
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 42
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 42
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 42
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 43
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 43
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 43
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 44
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 44
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 44
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 45
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 45
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 45
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 46
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 46
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 46
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 47
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 47
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 47
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 47
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 48
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 48
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 48
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 49
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 49
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 49
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 49
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 50
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 50
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 50
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 50
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 51
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 51
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 51
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 52
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 52
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 52
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 52
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 53
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 53
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 53
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 54
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 54
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 54
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 55
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 55
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 55
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 55
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 56
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 56
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 56
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 56
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 57
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 57
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 57
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 57
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 58
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 58
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 58
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 59
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 59
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 59
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 59
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 60
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 60
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 60
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 61
EXEC AssignPartnerToConference @PartnerID = 4, @ConferenceID = 61
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 61
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 61
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 62
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 62
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 62
EXEC AssignPartnerToConference @PartnerID = 1, @ConferenceID = 63
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 63
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 63
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 64
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 64
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 64
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 64
EXEC AssignPartnerToConference @PartnerID = 8, @ConferenceID = 65
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 65
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 65
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 66
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 66
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 66
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 67
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 67
EXEC AssignPartnerToConference @PartnerID = 10, @ConferenceID = 67
EXEC AssignPartnerToConference @PartnerID = 2, @ConferenceID = 68
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 68
EXEC AssignPartnerToConference @PartnerID = 7, @ConferenceID = 68
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 68
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 69
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 69
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 69
EXEC AssignPartnerToConference @PartnerID = 9, @ConferenceID = 69
EXEC AssignPartnerToConference @PartnerID = 5, @ConferenceID = 70
EXEC AssignPartnerToConference @PartnerID = 3, @ConferenceID = 70
EXEC AssignPartnerToConference @PartnerID = 6, @ConferenceID = 70
